PDLocals = {
--enemies
  ["Sheep: 100 health, 1 gold each."] = "Sheep: 100 health, 1 gold each.",
  ["Cats: 150 health, 2 gold each."] = "Cats: 150 health, 2 gold each.",
  ["Snakes: 200 health, 2 gold each."] = "Snakes: 200 health, 2 gold each.",
  ["Bats: 125 health, 3 gold each.  Immune to cannon towers!"] = "Bats: 125 health, 3 gold each.  Immune to cannon towers!",
  ["Boars: 300 health, 3 gold each."] = "Boars: 300 health, 3 gold each.",
  ["Panthers: 300 health, 4 gold each.  Increased speed!"] = "Panthers: 300 health, 4 gold each.  Increased speed!",
  ["Bears: 400 health, 4 gold each.  Boss next level!"] = "Bears: 400 health, 4 gold each.  Boss next level!",
  ["BOSS - Angry Cow: 4500 health, 50 gold."] = "BOSS - Angry Cow: 4500 health, 50 gold.",
  ["Gnomes: 350 health, 6 gold each.  Increased group size!"] = "Gnomes: 350 health, 6 gold each.  Increased group size!",
  ["Dwarves: 650 health, 7 gold each."] = "Dwarves: 650 health, 7 gold each.",
  ["Humans: 650 health, 8 gold each.  Increased speed!"] = "Humans: 650 health, 8 gold each.  Increased speed!",
  ["Night Elves: 850 health, 9 gold each.  Boss next level!"] = "Night Elves: 850 health, 9 gold each.  Boss next level!",
  ["BOSS - Knight: 9500 health, 100 gold."] = "BOSS - Knight: 9500 health, 100 gold.",
  ["Gyrocopters: 950 health, 11 gold each.  Immune to cannon towers!"] = "Gyrocopters: 950 health, 11 gold each.  Immune to cannon towers!",
  ["Bloodlusted Orcs: 1450 health, 12 gold each."] = "Bloodlusted Orcs: 1450 health, 12 gold each.",
  ["Imps: 1450 health, 13 gold each.  Immune to fire towers!"] = "Imps: 1450 health, 13 gold each.  Immune to fire towers",
  ["Leeches: 1950 health, 14 gold each.  Boss next level!"] = "Leeches: 1950 health, 14 gold each.  Boss next level!",
  ["BOSS - Avatar: 22500 health, 150 gold."] = "BOSS - Avatar: 22500 health, 150 gold.",
  ["Blood Elves: 1800 health, 16 gold each.  Increased group size!"] = "Blood Elves: 1800 health, 16 gold each.  Increased group size!",
  ["Trolls: 3250 health, 17 gold each."] = "Trolls: 3250 health, 17 gold each.",
  ["Forsaken: 3250 health, 18 gold each.  Increased speed!"] = "Forsaken: 3250 health, 18 gold each.  Increased speed!",
  ["Tauren: 4250 health, 19 gold each.  Boss next level!"] = "Tauren: 4250 health, 19 gold each.  Boss next level!",
  ["BOSS - Spectral Tiger: 47500 health, 200 gold."] = "BOSS - Spectral Tiger: 47500 health, 200 gold.",
  ["Demons: 4750 health, 23 gold each.  Immune to shadow towers!"] = "Demons: 4750 health, 23 gold each.  Immune to shadow towers!",
  ["Ghouls: 6550 health, 26 gold each."] = "Ghouls: 6550 health, 26 gold each.",
  ["Frozen Corpses: 6550 health, 29 gold each.  Immune to ice towers!"] = "Frozen Corpses: 6550 health, 29 gold each.  Immune to ice towers!",
  ["Soultakers: 8350 health, 32 gold each.  Boss next level!"] = "Soultakers: 8350 health, 32 gold each.  Boss next level!",
  ["Illidan: 92500 health, 350 gold."] = "Illidan: 92500 health, 350 gold.",
  ["Lava Spawns: 9250 health, 39 gold each.  Immune to fire towers!"] = "Lava Spawns: 9250 health, 39 gold each.  Immune to fire towers!",
  ["Abyssal Fiends: 10850 health, 43 gold each.  Immune to shadow towers!"] = "Abyssal Fiends: 10850 health, 43 gold each.  Immune to shadow towers!",
  ["Water Elementals: 12450 health, 47 gold each.  Immune to ice towers!"] = "Water Elementals: 12450 health, 47 gold each.  Immune to ice towers!",
  ["Nether Drakes: 15750 health, 51 gold each.  Boss next level!"] = "Nether Drakes: 15750 health, 51 gold each.  Boss next level!",
  ["Kil'Jaedan: 172500 health, 550 gold."] = "Kil'Jaedan: 172500 health, 550 gold.",
  ["Red Dragons: 17250 health, 62 gold.  Immune to fire towers!"] = "Red Dragons: 17250 health, 62 gold.  Immune to fire towers!",
  ["Black Dragons: 20250 health, 70 gold.  Immune to shadow towers!"] = "Black Dragons: 20250 health, 70 gold.  Immune to shadow towers!",
  ["Blue Dragons: 23250 health, 77 gold.  Immune to ice towers!"] = "Blue Dragons: 23250 health, 77 gold.  Immune to ice towers!",
  ["Bronze Dragons: 29250 health, 85 gold."] = "Bronze Dragons: 29250 health, 85 gold.",
  ["Green Dragons: 32250 health, 92 gold.  Boss next level!"] = "Green Dragons: 32250 health, 92 gold.  Boss next level!",
  ["C\'Thun: 350000 health, 1000 gold.  Boss next level!"] = "C\'Thun: 350000 health, 1000 gold.  Boss next level!",
  ["Yogg Saron: 500000 health, 1500 gold.  One more level!"] = "Yogg Saron: 500000 health, 1500 gold.  One more level!",
  ["Hula Girls: 50000 health, 1000 gold each.  Good luck!"] = "Hula Girls: 50000 health, 1000 gold each.  Good luck!",
  
--TooltipData
  ["Cannon Tower~A basic physical damage tower.  Cannot hit flying enemies.  Upgradeable for higher damage."] = "Cannon Tower~A basic physical damage tower.  Cannot hit flying enemies.  Upgradeable for higher damage.",
  ["%1$d gold\nMore damage.  Boom."] = "%1$d gold\nMore damage.  Boom.",
  ["%1$d gold\nEven more damage."] = "%1$d gold\nEven more damage",
  ["Arrow Tower~A simple tower which can attack both land and air units.  Upgradeable for higher damage."] = "Arrow Tower~A simple tower which can attack both land and air units.  Upgradeable for higher damage.",
  ["%1$d gold\nMore Damage.  Pew pew."] = "%1$d gold\nMore Damage.  Pew pew.",
  ["%1$d gold\nEven more damage."] = "%1$d gold\nEven more damage.",
  ["Fire Tower~A tower with the ability to char the flesh of enemies.  Early levels deal splash damage.  Upgradeable to AoE damage."] = "Fire Tower~A tower with the ability to char the flesh of enemies.  Early levels deal splash damage.  Upgradeable to AoE damage.",
  ["%1$d gold\nFires an explosive shell which explodes on impact for more splash damage."] = "%1$d gold\nFires an explosive shell which explodes on impact for more splash damage.",
  ["%1$d gold\nEngulfs the surrounding area, dealing damage to all enemies nearby."] = "%1$d gold\nEngulfs the surrounding area, dealing damage to all enemies nearby",
  ["Ice Tower~A frozen tower that chills the spirit of attackers.  Early levels slow their targets, while later levels slow all enemies in the area."] = "Ice Tower~A frozen tower that chills the spirit of attackers.  Early levels slow their targets, while later levels slow all enemies in the area.",
  ["%1$d gold\nFires an enchanted missile that slows the speed of attackers and deals more damage."] = "%1$d gold\nFires an enchanted missile that slows the speed of attackers and deals more damage.",
  ["%1$d gold\nChills the ground, slowing the speed of all enemies nearby but deals no damage."] = "%1$d gold\nChills the ground, slowing the speed of all enemies nearby but deals no damage.",
  ["Shadow Tower~A tower of darkness that consumes the soul of infidels.  Inflicts a high amount of damage over time, but multiple shadow effects do not stack.  Higher levels deal more damage."] = "Shadow Tower~A tower of darkness that consumes the soul of infidels.  Inflicts a high amount of damage over time, but multiple shadow effects do not stack.  Higher levels deal more damage.",
  ["%1$d gold\nFires a plagued bolt that inflicts more damage over time."] = "%1$d gold\nFires a plagued bolt that inflicts more damage over time.",
  ["%1$d gold\nFires a plagued bolt that deals significantly more damage over time."] = "%1$d gold\nFires a plagued bolt that deals significantly more damage over time.",
  ["%1$d gold\nChaotic energy infuses this tower, enabling it to deal significant single-target damage that pierces all immunities."] = "%1$d gold\nChaotic energy infuses this tower, enabling it to deal significant single-target damage that pierces all immunities.",
  ["Sell (|cffffffffX|r)~Sell this tower for a 75% refund of the current level\'s cost."] = "Sell (|cffffffffX|r)~Sell this tower for a 75% refund of the current level\'s cost.",
  ["Upgrade (|cffffffffU|r)"] = "Upgrade (|cffffffffU|r)",
  ["The Fury of Skoll~A fiery rage burns within the Amiran builders, allowing the creation of fire towers."] = "The Fury of Skoll~A fiery rage burns within the Amiran builders, allowing the creation of fire towers.",
  ["The Song of Lorelei~By harnessing the enchanted melody of the river maiden, the Amiran builders are able to craft ice towers."] = "The Song of Lorelei~By harnessing the enchanted melody of the river maiden, the Amiran builders are able to craft ice towers.",
  ["The Blight of the Abyss~Forces from the great unknown compel the Amiran builders, granting the ability to forge shadow towers."] = "The Blight of the Abyss~Forces from the great unknown compel the Amiran builders, granting the ability to forge shadow towers.",
  
--Towers
  ["None"] = "None",
  ["Splash damage"] = "Splash damage",
  ["AoE damage"] = "AoE damage",
  ["Single slow"] = "Single slow",
  ["AoE slow"] = "AoE slow",
  ["DoT damage"] = "DoT damage",
  ["Heavy DoT damage"] = "Heavy DoT damage",
  ["Chaos Damage"] = "Chaos Damage",

--PrimalDefense_StartLevel
  ["You've saved the Amirans from destruction!  All too easy..."] = "You've saved the Amirans from destruction!  All too easy...",
  
--reset game
  ["Level"] = "Level",
  ["Lives"] = "Lives",
  ["Gold"] = "Gold",
  ["Essence"] = "Essence",
  ["Fury of Skoll"] = "Fury of Skoll",
  ["Song of Lorelei"] = "Song of Lorelei",
  ["Blight of the Abyss"] = "Blight of the Abyss",
  ["Welcome to Primal Defense!"] = "Welcome to Primal Defense!",
  
--PrimalDefense_UpdateBlessingsTexts
  ["You are fully blessed."] = "You are fully blessed.",
  
--PrimalDefense_UpdateCostTexts
  ["Requires Blessing"] = "Requires Blessing",
  ["Cannon"] = "Cannon",
  ["Arrow"] = "Arrow",
  ["Fire"] = "Fire",
  ["Ice"] = "Ice",
  ["Shadow"] = "Shadow",
  
--PrimalDefense_MapTileOnClick
  ["Range"] = "Range",
  ["Damage"] = "Damage",
  ["Speed"] = "Speed",
  ["Ability"] = "Ability",
}